# https://www.tensorflow.org/guide/gpu#using_a_single_gpu_on_a_multi-gpu_system
# And Jeff Heaton class

import tensorflow as tf
from tensorflow.keras.callbacks import LambdaCallback
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.utils import get_file
import numpy as np
import random
import sys
import io
import requests
import re
import os
import pandas as pd
import time

BASE_PATH = "../../../../../local_data/"
DATA_PATH = BASE_PATH + "jheaton/input/"
OUTPUT_PATH = BASE_PATH + "practice/jheaton/pr_class_10_3_text_generation/"

os.system("mkdir -p " + OUTPUT_PATH)

filepath=DATA_PATH+"treasure_island.txt"
print(filepath)
raw_text = open(filepath, 'r').read()

processed_text = raw_text.lower()
processed_text = re.sub(r"[^\x00-\x7f]", r"", processed_text)
chars = sorted(list(set(processed_text)))

char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))


# cut the text in semi-redundant sequences of maxlen characters
maxlen = 40
step = 3
sentences = []
next_chars = []
for i in range(0, len(processed_text) - maxlen, step):
    sentences.append(processed_text[i : i + maxlen])
    next_chars.append(processed_text[i + maxlen])

df_sentences = pd.DataFrame(sentences, columns=["x_train"])
# print(df_sentences)
df_next_chars = pd.DataFrame(next_chars, columns=["y"])
# print(df_next_chars)
df_combined = pd.concat([df_sentences, df_next_chars], axis=1)
print(df_combined)

print("Vectorization...")
x = np.zeros((len(sentences), maxlen, len(chars)), dtype=bool)
y = np.zeros((len(sentences), len(chars)), dtype=bool)
for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        x[i, t, char_indices[char]] = 1
    y[i, char_indices[next_chars[i]]] = 1


np.set_printoptions(threshold=np.inf, linewidth=130)


print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices("GPU")))

# tf.debugging.set_log_device_placement(True)
tf.debugging.set_log_device_placement(False)

try:
    # Specify the GPU device
    print('Using /device:GPU:1')
    with tf.device("/device:GPU:1"):


        # build the model: a single LSTM
        print("Build model...")
        model = Sequential()
        model.add(LSTM(128, input_shape=(maxlen, len(chars))))
        model.add(Dense(len(chars), activation="softmax"))
        optimizer = RMSprop(learning_rate=0.01)
        model.compile(loss="categorical_crossentropy", optimizer=optimizer)
        model.summary()

        def on_epoch_end(epoch, _):
            print("******************************************************")
            print("----- saving model after Epoch: %d" % epoch)


            # Save model
            timestr = time.strftime("%Y%m%d-%H%M%S")
            # filename_time = f"treasure_val_loss_{val_loss[-1]:.2f}_epochs_{epochs}_date_{timestr}"
            filename_time = f"treasure_epochs_{epoch:04d}_date_{timestr}"
            filename_static = "pr_class_10_3_text_generation"
            fullpath = f"{OUTPUT_PATH}{filename_static}"
            print("Saving model to ", fullpath)
            model.save(fullpath + ".keras")
            fullpath = f"{OUTPUT_PATH}{filename_time}"
            print("Saving model to ", fullpath)
            model.save(fullpath + ".keras")

        # Ignore useless W0819 warnings generated by TensorFlow 2.0.
        # See https://github.com/tensorflow/tensorflow/issues/31308
        import logging, os

        logging.disable(logging.WARNING)
        os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
        # Fit the model
        print_callback = LambdaCallback(on_epoch_end=on_epoch_end)
        history = model.fit(x, y, batch_size=128, epochs=60, callbacks=[print_callback])

        # print(history.history.keys())
        # val_loss     = history.history["val_loss"]



except RuntimeError as e:
    print(e)
