# conda env create -f environment.yml
# conda info --envs
# conda remove -n ENVNAME --all


name: kd
channels:
  - pytorch
  - nvidia
  # - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm


  # - conda-forge::numpy=1.21.*
  # - nodejs=16.13.*

  # - pip
  # - pip:
  #   - Flask-Testing