# https://community.home-assistant.io/t/esp32-ledc-output-variable-frequency/618050

substitutions:
  devicename: pwm_generic
  friendlyname: pwm_generic
  fdevicename: ""
  ip: 192.168.0.178 # For static IP adressing
  ssid: "TP-LINK_MR3040_4B611E"
  password: ""

esphome:
  name: ${devicename}
  friendly_name: ${friendlyname}

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

preferences:
  flash_write_interval: 2min
    
wifi:
  ssid: ${ssid}
  password: ${password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${fdevicename}Fallback Hotspot
    password: "esphome1"
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.2
      subnet: 255.255.255.0
    
ota:
  - platform: esphome
    password: "esphome1"

web_server:
  port: 80
  version: 3
  local: true
  log: true

debug:
  update_interval: 10s

logger:
  level: Debug

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True
    frequency: 400khz
  - id: bus_b
    sda: GPIO16
    scl: GPIO17
    scan: True
    frequency: 800khz
    
switch:
  - platform: restart
    name: "${device_name} REBOOT"

number:
  - platform: template
    name: PWM %
    optimistic: true
    initial_value: 30 
    min_value: 0
    max_value: 100
    step: 1
    mode: slider
    on_value:
      then:
        lambda: 'id(PWM).set_level(x/100);'

output:
  - platform: ledc
    pin: GPIO2
    id: PWM
    frequency: 100Hz
    # inverted: true
